# environment.yml
name: green-mapper
channels:
  - conda-forge
dependencies:
  - python=3.10
  - requests
  - gitpython
  - numpy
  - pandas
  - geopandas
  - shapely
  - rasterio
  - xarray
  - matplotlib
  - pyyaml
  - omegaconf
  - black