default:
    
    # Specify model start and end here
    points:
        start: "SW1A1AA" # Buckingham Palace
        end: "EC3N4AB" # Tower of London

    # these parameters match the parameters outlined on TFL API website:
    # https://api.tfl.gov.uk/swagger/ui/index.html?url=/swagger/docs/v1#!/Journey/Journey_JourneyResults
    route_params:
        walkingSpeed: "fast"
        bikeProficiency: "fast"
        alternativeCycle: "true"
        alternativeWalking: "true"
        usemMulitModalCall: "true"
        includeAlternativeRoutes: "true"
